package view;


import Modelo.Operacion;

import javax.swing.JOptionPane;
import java.awt.Color;


public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
      initComponents();
        setSize(800,600);      
        setLocationRelativeTo(null);
      
        peso.setContentAreaFilled(false);
        peso.setBorderPainted(false);
        peso.setFocusPainted(false);
        peso.setOpaque(false);
        
        pan1.setOpaque(true); 
        pan1.setBackground(new Color(0, 0, 0, 144));
        pan2.setOpaque(true); 
        pan2.setBackground(new Color(102, 102, 102, 144));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pan1 = new javax.swing.JPanel();
        tx_email = new javax.swing.JTextField();
        tx_ingresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tx_contraseña = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        peso = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pan2.setBackground(new java.awt.Color(102, 102, 102));
        pan2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2778718.png"))); // NOI18N
        pan2.add(jLabel1);
        jLabel1.setBounds(100, 100, 110, 110);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        pan2.add(jLabel8);
        jLabel8.setBounds(10, 300, 300, 0);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Your first steps to success.");
        pan2.add(jLabel12);
        jLabel12.setBounds(180, 400, 310, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        pan2.add(jLabel15);
        jLabel15.setBounds(170, 400, 310, 25);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("BIENVENIDOS");
        pan2.add(jLabel16);
        jLabel16.setBounds(40, 0, 240, 90);

        getContentPane().add(pan2);
        pan2.setBounds(100, 80, 320, 430);

        pan1.setBackground(new java.awt.Color(0, 0, 0));
        pan1.setForeground(new java.awt.Color(102, 0, 0));
        pan1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pan1.setLayout(null);

        tx_email.addActionListener(this::tx_emailActionPerformed);
        pan1.add(tx_email);
        tx_email.setBounds(10, 180, 260, 30);

        tx_ingresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tx_ingresar.setText("Login");
        tx_ingresar.addActionListener(this::tx_ingresarActionPerformed);
        pan1.add(tx_ingresar);
        tx_ingresar.setBounds(60, 300, 120, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA:");
        pan1.add(jLabel6);
        jLabel6.setBounds(10, 220, 140, 16);
        pan1.add(tx_contraseña);
        tx_contraseña.setBounds(10, 240, 260, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CEDULA:");
        pan1.add(jLabel7);
        jLabel7.setBounds(10, 160, 90, 16);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN");
        pan1.add(jLabel5);
        jLabel5.setBounds(80, 30, 140, 90);

        peso.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        peso.setText("REGISTER");
        peso.addActionListener(this::pesoActionPerformed);
        pan1.add(peso);
        peso.setBounds(190, 400, 100, 21);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Puede registrarse en");
        pan1.add(jLabel14);
        jLabel14.setBounds(80, 400, 240, 20);

        getContentPane().add(pan1);
        pan1.setBounds(420, 80, 300, 430);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp7122383.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_emailActionPerformed

    private void tx_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_ingresarActionPerformed
        String cedula = tx_email.getText(); // sigue usando el mismo campo, pero ahora es cédula
    String contraseña = tx_contraseña.getText();

    if(cedula.isEmpty() || contraseña.isEmpty()){
        JOptionPane.showMessageDialog(null, "Campo vacio");
        tx_email.setText("");
        tx_contraseña.setText("");
        return;
    }

    // Validar que la cédula sea numérica
    if(!cedula.matches("[0-9]+")){
        JOptionPane.showMessageDialog(null, "La cédula debe ser numérica");
        tx_email.setText("");
        return;
    }

    // Validar contraseña
    String contraseña_verifi = Operacion.Contraseña(contraseña);
    if(contraseña_verifi.length() < 6){
        tx_contraseña.setText("");
        return;
    }

    // Aquí luego validas usuario real
    JOptionPane.showMessageDialog(null, "Login correcto");

    // abrir panel

    }//GEN-LAST:event_tx_ingresarActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        register r = new register();
        r.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_pesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JButton peso;
    private javax.swing.JTextField tx_contraseña;
    private javax.swing.JTextField tx_email;
    private javax.swing.JButton tx_ingresar;
    // End of variables declaration//GEN-END:variables
}
