/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import javax.swing.JOptionPane;

import Modelo.Usuarios;
/**
 *
 * @author MachineWar
 */
public class register extends javax.swing.JFrame {
    

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setSize(800,600);      
        setLocationRelativeTo(null);
        
        pan1.setOpaque(true); 
        pan1.setBackground(new Color(60,63,65, 144));
        pan2.setOpaque(true); 
        pan2.setBackground(new Color(204, 204, 204, 144));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtBarrio = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pan2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pan1.setBackground(new java.awt.Color(102, 102, 102));
        pan1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("NOMBRE:");
        pan1.add(jLabel3);
        jLabel3.setBounds(20, 60, 84, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("CEDULA: ");
        pan1.add(jLabel4);
        jLabel4.setBounds(20, 110, 90, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONO: ");
        pan1.add(jLabel7);
        jLabel7.setBounds(10, 160, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("BARRIO: ");
        pan1.add(jLabel5);
        jLabel5.setBounds(30, 260, 90, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("CONTRASEÑA:");
        pan1.add(jLabel6);
        jLabel6.setBounds(0, 350, 127, 25);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        pan1.add(txtNombre);
        txtNombre.setBounds(120, 60, 170, 30);
        pan1.add(txtCedula);
        txtCedula.setBounds(120, 110, 170, 30);
        pan1.add(txtTelefono);
        txtTelefono.setBounds(120, 160, 170, 30);
        pan1.add(txtBarrio);
        txtBarrio.setBounds(120, 260, 170, 30);
        pan1.add(txtPassword);
        txtPassword.setBounds(130, 350, 160, 30);
        pan1.add(txtEmail);
        txtEmail.setBounds(120, 210, 170, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("E-MAIL:");
        pan1.add(jLabel8);
        jLabel8.setBounds(30, 210, 67, 25);

        getContentPane().add(pan1);
        pan1.setBounds(110, 60, 300, 470);

        pan2.setBackground(new java.awt.Color(153, 153, 153));
        pan2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("REGISTER");
        pan2.add(jLabel9);
        jLabel9.setBounds(70, 70, 130, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2778718.png"))); // NOI18N
        pan2.add(jLabel2);
        jLabel2.setBounds(80, 130, 110, 90);

        Ingresar.setBackground(new java.awt.Color(102, 102, 102));
        Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("REGISTER");
        Ingresar.addActionListener(this::IngresarActionPerformed);
        pan2.add(Ingresar);
        Ingresar.setBounds(50, 250, 150, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Le damos la bienvenida a nuestro ");
        pan2.add(jLabel10);
        jLabel10.setBounds(20, 340, 190, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("sistema de ofertas laborales y ");
        pan2.add(jLabel11);
        jLabel11.setBounds(20, 360, 240, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("busqueda de servicios.");
        pan2.add(jLabel12);
        jLabel12.setBounds(20, 380, 190, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel13.setText("Your first steps to success.");
        pan2.add(jLabel13);
        jLabel13.setBounds(140, 440, 310, 25);

        getContentPane().add(pan2);
        pan2.setBounds(410, 60, 270, 470);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp7122383.jpg"))); // NOI18N
        jLabel1.setText("700,590");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
       String nombre = txtNombre.getText();
       String cedula = txtCedula.getText();
       String email = txtEmail.getText();
       String telefono = txtTelefono.getText();
       String barrio = txtBarrio.getText();
       String pass = txtPassword.getText();

       if (nombre.isEmpty() || cedula.isEmpty() || email.isEmpty() || telefono.isEmpty() || barrio.isEmpty() || pass.isEmpty()) {
           JOptionPane.showMessageDialog(null, "Debe completar todos los campos.");
           return;
       }

       Usuarios u = new Usuarios(nombre, cedula, telefono, barrio, pass);

       Usuarios.agregar(u);

       Usuarios.mostrarTodos();

       JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");

       login lo = new login();
       lo.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
